name: CI-docstrings

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docstrings:
    name: docstrings
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install
      run: pip install -e .
    - name: doctstring check
      run: |
        pytest --doctest-modules pyamg
