name: wheels

on:
  push:
  workflow_dispatch:

jobs:
  build_wheels:

    name: Build wheel cp${{ matrix.python }}-${{ matrix.platform_id }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Find the latest tagged version
      uses: oprypin/find-latest-tag@v1
      with:
        repository: pyamg/pyamg
      id: pyamg_version

    - name: Check the tag
      run: echo "The tag found is ${{ steps.pyamg_version.outputs.tag }}"

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.pyamg_version.outputs.tag }}

    - name: Check the checkout
      run: git log
